# Generated by Django 5.0.1 on 2024-01-23 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='leaderboard',
            options={'verbose_name_plural': 'Leaderboard'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'quizzes'},
        ),
        migrations.AlterModelTable(
            name='category',
            table='Competition_category',
        ),
        migrations.AlterModelTable(
            name='leaderboard',
            table='Competition_leaderboard',
        ),
        migrations.AlterModelTable(
            name='question',
            table='Competition_questions',
        ),
        migrations.AlterModelTable(
            name='quiz',
            table='Competition_quiz',
        ),
    ]
