# Generated by Django 5.0.1 on 2024-01-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0005_alter_options_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='option',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(max_length=300),
        ),
    ]
