# Generated by Django 5.0.1 on 2024-01-24 06:09

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0006_alter_options_option_alter_question_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
        migrations.AddField(
            model_name='quiz',
            name='category',
        field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.category'),
        preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='options',
            unique_together={('question', 'is_answer')},
        ),
    ]
