# Generated by Django 5.0.1 on 2024-01-24 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0007_remove_question_category_quiz_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='category',
        ),
        migrations.RemoveField(
            model_name='leaderboard',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='leaderboard',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='options',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='options',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Leaderboard',
        ),
        migrations.DeleteModel(
            name='Options',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
