# Generated by Django 5.0.1 on 2024-01-24 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0009_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='options',
            unique_together=set(),
        ),
    ]
